### ISSUE TITLE
요구사항 확인 및 서비스 기획

### ISSUE THREAD

**Issue by flowersayo** [Open-SW-platform/ToDoApp#1]
# 📆 날짜
2021.11.08 ~

# 📙 내용

- [ ] 어플 이름 정하기

- [ ] 어플 기능 정하기

# 🔩 요구사항 확인

**Required features (basic)** 

• Enter/edit/remove a to-do item 
• Set the due date per to-do item
• Show all added to-do items 
• Check/uncheck a to-do item to mark completion 
• Select/deselect specific/all to-do items 
• Delete specific/all to-do items

**Required features (intermediate)**

• Change the order of to-do items 
• Show only the complete/incomplete to-do items (filtering)
• Allow users to set a category for each to-do item (grouping) 
• Sort to-do items in terms of the added date, due date across categories 
• Sort to-do items in terms of the added date, due date within each category 

**Required features (difficult)**

• Add a comment to a to-do list 
• View details about to-do-list

# 🖋 서비스 기획 / 구현

# 📌 역할분담

@akimcse 
@chaeri93 
@Yevin-WIN 
@flowersayo

**Comment by akimcse** [comment]
정리 감사합니다!

오늘(1109) 회의에서는
- [ ] 어플 이름 확정
- [x] 기능 명세서 작성
- [x] 프로토타입 스케치 역할분담

이렇게 3가지 다뤄보는 게 어떨까요?
기능명세서가 있으면 스케치 구상하기도 쉽고, 나중에 분담해서 개발할 때 혼동하는 일도 없을 것 같아서 다 모였을 때 한번 작성해두면 좋을 것 같아요!
